#!/bin/sh

ulimit -c unlimited
rm core
all=`ls *.pcb | grep -v "[.]new[.]pcb$\|[.]orig[.]pcb$\|^[.]"`
num_all=`echo "$all" | wc -l`

cnt=0
for n in $all
do
	cnt=$(($cnt+1))
	echo "----------------------$n"
	echo "----------------------$n $cnt/$num_all" >&2
	pcb-rtrip $n | grep -v "PCBChanged\|readres=-1\|No PCB loaded\|pcb-gpmi hid is loaded\|has no font information, using default font"
	if test -f core
	then
		mv core $n.core
	fi
done > All.log

