#!/bin/sh

header='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- AUTOGENERATED FILE, DO NOT EDIT ; generator is action_compiler.sh (run make) -->
<html>
<body>
<h1> pcb-rnd actions </h1>
<h2> Action reference (details) </h2>
'

footer='
</body>
</html>
'


compile()
{
	tr "\n\r\t" "   " < $1 | sed "s@<@\n<@g;s@>@>\n@g;" | tee A | awk -v "current=$1" '
	BEGIN {
		q="\""
		sub("^.*/", "", current)
		sub(".html$", "", current)
		print ""
		print "<h3 id=" q current q ">" current "</h3>"
		print "<p>"
	}

	function strip(s) {
		sub("^[ \t]*", "", s)
		sub("[ \t]*$", "", s)
		return s
	}

	function read_tag(tag,    tmp1,tmp2) {
		getline tmp1
		getline tmp2
		if (tmp2 ~ "</" tag)
			return tmp1
		print "Error: expected closing tag " tag " in line " NR " of " current > "/dev/stderr"
		exit(1)
	}

	/^<arg>/ {
		arg = read_tag("arg")
		print "<i>" arg "</i>"
		next
	}

	/^<example>/ {
		ex = read_tag("example")
		print "Example:", ex, "<br>"
		next
	}

	/^<act>/ {
		act = tolower(read_tag("act"))
		print "<a href=" q "#" act q ">" act "</a>"
		next
	}

	{
		print
	}
	'
}

if test "$1" == "HEADER"
then
	echo "$header"
	exit 0
fi

if test "$1" == "FOOTER"
then
	echo "$footer"
	exit 0
fi

compile $1
