#!/bin/sh

#@@example acy(300)

#@@purpose Generate axial lead tru-hole component

#@@desc Generate axial lead tru-hole component with 2 pins (typical use: resistor)
#@@params spacing,pol,dia

#@@param:spacing spacing between the two pins
#@@pol: how to mark polarity: none, sign, bar (optional; default: do not mark polarity)
#@@dia: body diameter - affects the silk rectangle (optional; default: spacing/12)

#@@include common.awk

awk -f `dirname $0`/common.awk -f `dirname $0`/acy.awk -v "args=$*"

