#!/bin/sh

#@@include tqfp

#@@example lqfp(32,7x7,0.8)

#@@purpose Generate LQFP packages
#@@desc Generate LQFP packages - a simplified frontend to qf() - 
#@@desc look up 3..4 data in the datasheet and get a regular LQFP footprint!
#@@desc NOTE: some of the qf() parameters can be also used.

awk -f `dirname $0`/common.awk -f `dirname $0`/tqfp.awk -f `dirname $0`/qf.awk -v "args=$*" -v gen=`basename $0`

