#!/bin/sh

#@@example morse(hello world, 1mm)

#@@purpose Generate morse code

#@@desc Generate the specified morse code as silk lines and dots; installation: copy morse* to pcblib/parametric
#@@params text,dit_width,page
#@@thumbsize 2

#@@param:text ASCII text to encode

#@@param:dit_width width of a dit
#@@dim:dit_width

#@@param:page code page to use to encode characters
#@@optional:page
#@@enum:level:A
#@@enum:level:B
#@@default:B

awk -f `dirname $0`/common.awk -f `dirname $0`/morse.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

