#!/bin/sh

#@@example tqfp(32,7x7,0.8)

#@@purpose Generate TQFP packages
#@@desc Generate TQFP packages - a simplified frontend to qf() - 
#@@desc look up 3..4 data in the datasheet and get a regular TQFP footprint!
#@@desc NOTE: some of the qf() parameters can be also used.

#@@params:pins,size,pitch,cpad_size

#@@param:pin total number of pins (leads); must be divisible by 4
#@@param:size a single integer N or NxN or NxNxH; body dimension (width or height of the plastic body) in mm
#@@param:pitch lead pitch (distance between the centerline of two adjacent leads), in mm; must be one of 0.4, 0.5, 0.65

#@@param:cpad_size width (and height) of the central pad, in mm
#@@optional:cpad_size
#@@default:cpad_size empty, there's no central pad

awk -f `dirname $0`/common.awk -f `dirname $0`/tqfp.awk -f `dirname $0`/qf.awk -v "args=$*" -v gen=`basename $0`

