cdt_test.o: cdt_test.c cdt.h typedefs.h point.h ../libcdtr/list/list.h \
   edge.h \
 triangle.h
cdt.o: cdt.c cdt.h typedefs.h point.h ../libcdtr/list/list.h \
   edge.h \
 triangle.h
point.o: point.c point.h typedefs.h ../libcdtr/list/list.h \
 ../libcdtr/list/list.c 
edge.o: edge.c edge.h typedefs.h ../libcdtr/list/list.h \
 ../libcdtr/list/list.c 
triangle.o: triangle.c triangle.h typedefs.h ../libcdtr/list/list.h \
 ../libcdtr/list/list.c 
