#!/bin/sh

#@@example connector(2, 3, silkmark=external)

#@@purpose Generate pin-array connectors (e.g. headers).

#@@desc Generate thru-hole connectors that consits of an array of
#@@desc evenly spaced pins, a plain frame and some optional pin marks
#@@desc on the silk layer.

#@@params nx, ny, spacing, silkmark

#@@param:nx number of pins in the X direction (mandatory, no default)
#@@param:ny number of pins in the Y direction (mandatory, no default)
#@@param:spacing spacing between the pins (in mil, or in mm using the mm suffix; optional, default is 100 mil)
#@@param:silkmark how to mark pin 1; values: square, external, angled, none (optional; default is square)

awk -f `dirname $0`/common.awk -f `dirname $0`/connector.awk -v "args=$*"

