#!/bin/sh

#@@example dip(18)

#@@purpose Generate classic DIP packages.

#@@desc Generate thru-hole DIP packages with variable number of pins and
#@@desc row spacing
#@@params n, spacing

#@@param:n number of pins
#@@param:spacing spacing between the two rows of pins (in mil, or in mm using the mm suffix; optional, default is 100 mil)

#@@include common.awk

awk -f `dirname $0`/common.awk -f `dirname $0`/dip.awk -v "args=$*"

