/* Autogenerated by cquote.c - DO NOT EDIT */
/* (Using character array instead of string literal for long strings) */
const char drc_query_conf_internal_arr[] = {0};
const char *drc_query_conf_internal = drc_query_conf_internal_arr;
