#!/bin/bash
# Generated by gpmi-config
# GPMI fingerprint: Install.sh-ext-pkg

# Name of the package group
pkg_grp_name=pcb-gpmi

gpmi_fstools=`gpmi-config --fstools`

if test -z "$gpmi_fstools"
then
	echo "Error: Can't find gpmi-config or it doesn't work;"
	echo "is GPMI installed?"
	exit
fi

# Include all the gpmi config variables
. $gpmi_fstools

local_gpmi_install_path_pkg_lib=${install_root}${gpmi_install_path_pkg_lib}
local_gpmi_install_path_pkg_include=${install_root}${gpmi_install_path_pkg_include}

# Process command line arguments
while getopts "HlucL:" Option
do
	case $Option in
		H) local_gpmi_install_path_pkg_lib=${gpmi_istall_path_user_pkg_lib} ; local_gpmi_install_path_pkg_include=${gpmi_istall_path_user_pkg_mod} ;;
		l) with_fs_cp=$with_fs_ln ;;
		u) $with_fs_rm ${local_gpmi_install_path_pkg_lib}/$pkg_grp_name; $with_fs_rm ${local_gpmi_install_path_pkg_include}/$pkg_grp_name; exit ;;
		c) inst_install_do_copy;;
		L) with_fs_ln=$OPTARG ;;
	esac
done

# Create package group dir
$with_fs_mkdir ${local_gpmi_install_path_pkg_lib}/$pkg_grp_name
$with_fs_mkdir ${local_gpmi_install_path_pkg_include}/$pkg_grp_name

pwd=`pwd`

# Copy all files compiled
for n in *-static.o
do
	name=${n%-static.o}
	header=`echo $name | sed "s/$/.h/"`
	for m in -static.o .a .so .dep .dlc
	do
		fn=${name}${m}
		if test -f $fn
		then
			$with_fs_cp $pwd/$fn ${local_gpmi_install_path_pkg_lib}/$pkg_grp_name/$fn
		fi
	done
	if test -f $header
	then
		$with_fs_cp $pwd/$header ${local_gpmi_install_path_pkg_include}/$pkg_grp_name/$header
	fi
done
