#!/bin/sh

#@@example dip(18)

#@@purpose Generate classic DIP packages.

#@@desc Generate thru-hole DIP packages with variable number of pins and
#@@desc row spacing
#@@params n, spacing

#@@param:n number of pins

#@@param:spacing spacing between the two rows of pins
#@@dim:spacing
#@@optional:spacing
#@@default:spacing 100 mil

#@@include common_subc.awk

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/dip.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

