#!/bin/sh

# Reference: Microchip Packaging Specification DS00000049BX (en012702.pdf), SSOP

#@@example plcc(20)

#@@purpose Generate PLCC packages
#@@desc Generate square PLCC packages - a simplified frontend to qf() - 
#@@desc only the number of pins is really needed for a square PLCC footprint!
#@@desc NOTE: some of the qf() parameters can be also used; PLCC32 is non-square, and can not be properly generated using this generator.

#@@params pins,size,pitch,cpad_size

#@@param:pins total number of pins (leads); must be divisible by 4

#@@param:size a single integer N or NxN or NxNxH; outmost dimensions (width or height of the package, leads included) in mil
#@@optional:size
#@@default:size calculated from total number of pins and pitch

#@@param:pitch lead pitch (distance between the centerline of two adjacent leads), in mil; must be 50 for now
#@@optional:pitch
#@@default:pitch 50mil

#@@param:cpad_size width (and height) of the central pad, in mil
#@@optional:cpad_size
#@@default:cpad_size empty, there's no central pad

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/plcc.awk -f `dirname $0`/qf.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

