#!/bin/sh

#@@example so(14)

#@@purpose Generate SO and SO-like packages.

#@@desc Generate SO packages with variable number of pins and
#@@desc row spacing
#@@params n, row_spacing, pad_spacing

#@@param:n number of pins

#@@param:row_spacing spacing between the two rows of pads: distance between the end of the first and last pins
#@@dim:row_spacing
#@@optional:row_spacing
#@@default:row_spacing 250 mil


#@@param:pad_spacing spacing between the centerline of two pads
#@@dim:pad_spacing
#@@optional:pad_spacing
#@@default:pad_spacing 50 mil


#@@param:ext_bloat how much longer the pad should extend outwards from the end-point of the pin
#@@dim:ext_bloat
#@@optional:ext_bloat
#@@default:ext_bloat 10 mil

#@@param:int_bloat how much longer the pad should extend inwards from the end-point of the pin
#@@dim:int_bloat
#@@optional:int_bloat
#@@default:int_bloat 55 mil

#@@include common_subc.awk

#@@over@ignore::pin_

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/so.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

