#!/bin/sh

# Reference: Microchip Packaging Specification DS00000049BX (en012702.pdf), SSOP

#@@example ssop(14)

#@@purpose Generate SSOP packages.

#@@desc Generate SSOP packages with variable number of pins and
#@@desc row spacing

#@@include so
#@@include common_subc.awk

#@@over@default:pad_spacing 0.65 mm
#@@over@default:row_spacing 7.8 mm
#@@over@default:int_bloat 0.5 mm
#@@over@default:ext_bloat 0.13 mm
#@@over@default:pad_thickness 0.45 mm

defaults='
?pad_spacing=0.65mm,
?row_spacing=7.8mm,
?int_bloat=0.5mm,
?ext_bloat=0.13mm,
?rarc=25,
?silk_ext_x=18,
?silk_ext_y=22,
?pad_thickness=0.45mm
'

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/so.awk -v "args=$defaults,$*" -v gen=`basename $0` -v "genfull=$0"

