.\" pcb-rnd - manual
.\" Copyright (C) 2016 Tibor 'Igor2' Palinkas
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\" 
.\" Contact: pcb-rnd-man[removethis]@igor2.repo.hu
.TH fp2anim 1 2016-12-27 "" "pcb-rnd manual"
.SH NAME
fp2anim - convert a gEDA/PCB footprint to animator script
.SH SYNPOSIS
.nf
.sp
\fBfp2anim [\fIoptions\fB] [\fIinputfile\fB]
.fi
.SH DECSRIPTION

.BR fp2anim
converts a footprint to a script that can be run through animator(1). It's main use is to have a automated, light-weight footprint preview generator on hosts where installing pcb-rnd would be too expensive (e.g. on web servers). 
.PP
If \fIinputfile\fR is not specified, 
.BR fp2anim
reads its STDIN for the footprint.
.SH OPTIONS


.TP

.B --photo 
draw the footprint in "photo realistic mode" 
.TP

.B -p 
same as --photo 
.TP

.B --grid unit 
set grid unit e.g. to mm or mil 
.TP

.B -g unit 
same as --grid 
.TP

.B --mm 
use an mm grid instead of a mil grid; shorthand for -g mm 
.TP

.B --diamond 
draw a small diamond to mark at footprint origin 
.TP

.B --annotation types 
turn on annotation types; types is a string that may consist "pins" for pin numbers, "dimname" and "dimvalue" for dimension names and values and "background" for drawing a background under annotation text
.PP

