.TH gsch2pcb-rnd 1 "June 21st, 2023" "pcb-rnd"
.SH NAME
gsch2pcb-rnd - dummy transitional utility
.SH SYNOPSIS
\fBgsch2pcb-rnd\fR
.SH DESCRIPTION
.PP
\fBgsch2pcb-rnd\fR is dummy transitional utility that prints instructions
for the user about switching to a modern workflow.

.SH SEE ALSO
\fBpcb-rnd\fR(1)
