.\" pcb-rnd - manual
.\" Copyright (C) 2016 Tibor 'Igor2' Palinkas
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\" 
.\" Contact: pcb-rnd-man[removethis]@igor2.repo.hu
.TH txt2bxl 1 2020-04-18 "" "pcb-rnd manual"
.SH NAME
txt2bxl - encode a BXL file provided in plain text and save binary
.SH SYNPOSIS
.nf
.sp
\fBtxt2bxl \fIoutfile.bxl\fB &lt; \fIinfile.txt\fB
.fi
.SH DECSRIPTION

.BR txt2bxl
reads and encodes a text bxl file in its standard input and saves the resulting binary bxl file on the file name specified in the command line argument.
