ROOT=../../..
TUTDIR=$(DOCDIR)/tutorial/17_sch


all:

install_all:
	$(SCCBOX) mkdir -p $(TUTDIR)
	$(SCCBOX) $(HOW) 7805_gschem.sch $(TUTDIR)/7805_gschem.sch
	$(SCCBOX) $(HOW) sch.png $(TUTDIR)/sch.png
	$(SCCBOX) $(HOW) index.html $(TUTDIR)/index.html

install:
	$(MAKE) -f Makefile.inst install_all HOW="install -f"

linstall:
	$(MAKE) -f Makefile.inst install_all HOW="install -f -l --absolute "

uninstall:
	$(MAKE) -f Makefile.inst install_all HOW="install -u"

include $(ROOT)/Makefile.conf
