/* Autogenerated by cquote.c - DO NOT EDIT */
/* (Using character array instead of string literal for long strings) */
const char accel_net_menu_arr[] = {
	'h','a',':','r','n','d','-','m','e','n','u','-','v','1',' ','{',
	'\n',
	'\t','l','i',':','a','n','c','h','o','r','e','d',' ','{','\n',
	'\t','\t','h','a',':','@','i','m','p','o','r','t','_','s','c',
	'h',' ','{','\n',
	'\t','\t','\t','l','i',':','s','u','b','m','e','n','u',' ','{',
	'\n',
	'\t','\t','\t','\t','h','a',':','L','o','a','d',' ','O','r','c',
	'a','d',' ','P','C','B',' ','I','I',' ','n','e','t','l','i','s',
	't',' ','f','i','l','e',' ','=',' ','{',' ','a','c','t','i','o',
	'n','=','L','o','a','d','O','r','c','a','d','N','e','t','F','r',
	'o','m','(',')',' ','}','\n',
	'\t','\t','\t','}','\n',
	'\t','\t','}','\n',
	'\t','}','\n',
	'}','\n',
	0};
const char *accel_net_menu = accel_net_menu_arr;
