#!/bin/sh
for n in `find . -name "*.[chly]"`
do
sed '
{

s/COORD_TO_MIL/PCB_COORD_TO_MIL/g
s/MIL_TO_COORD/PCB_MIL_TO_COORD/g
s/COORD_TO_MM/PCB_COORD_TO_MM/g
s/MM_TO_COORD/PCB_MM_TO_COORD/g
s/COORD_TO_INCH/PCB_COORD_TO_INCH/g
s/INCH_TO_COORD/PCB_INCH_TO_COORD/g

s/RAD_TO_DEG/PCB_RAD_TO_DEG/g
s/TAN_22_5_DEGREE_2/PCB_TAN_22_5_DEGREE_2/g
s/COS_22_5_DEGREE/PCB_COS_22_5_DEGREE/g
s/TAN_30_DEGREE/PCB_TAN_30_DEGREE/g
s/TAN_60_DEGREE/PCB_TAN_60_DEGREE/g
s/LN_2_OVER_2/PCB_LN_2_OVER_2/g
s/UNSCALE_TEXT/PCB_UNSCALE_TEXT/g
s/SCALE_TEXT/PCB_SCALE_TEXT/g
s/M180/PCB_M180/g
}
' -i $n
done
