#!/bin/sh

genpage()
{
	local dir scripts name desc
	
	dir="$1"
	scripts=`cd $dir && ls ex.*`
	name=`cat $dir/ID.name`
	desc=`cat $dir/ID.desc`
	./tags < "$dir/ex.html" | awk -v "fn_ref=REF" -v "scripts=$scripts" -v "name=$name" -v "desc=$desc" '
	BEGIN {
		while((getline < fn_ref) > 0) {
			REF[$2] = $3
		}
		print "<html><body>"
		print "<!-- ******* DO NOT EDIT THIS FILE, it is generated by rosetta_genpages.sh ******* -->"
		print "<h1>" name "</h1>"
		print desc

		print "<H2> Example implementations </H2>"
		v = split(scripts, S, "[\r\n]+")
		for(n = 1; n <= v; n++) {
			if (S[n] == "ex.html")
				continue
			lang=S[n]
			sub("^ex[.]", "", lang)
			if (n != 1)
				print " | "
			print "<a href=\"" S[n] "\">" lang "</a>"
		}

		print "<h2> Explanation, step by step </h2>"
	}
	/^<ref>/ {
		gsub("</?ref>", "", $0)
		name=$0
		gsub("[ \t]*", "", name)
		if (name in REF) {
			link_begin="<a href=\"../" REF[name]  "\">"
			link_end = "</a>"
		}
		else {
			link_begin=""
			link_end=""
		}
		print "<i>" link_begin $0 link_end "</i>"
		next
	}

	{ print $0 }

	' > "$dir/index.html"

}

for n in ../rosetta/*
do
	if test -d "$n"
	then
		genpage "$n"
	fi
done