#!/bin/sh

#@@example alf(300, schottky)

#@@purpose Generate ALF: axial lead through-hole component for diodes

#@@desc Generate axial lead through-hole component with 2 pin diodes
#@@params spacing,type,dia
#@@thumbsize 2

#@@param:spacing spacing between the two pins
#@@dim:spacing

#@@param:type symbol type
#@@enum:type:normal
#@@enum:type:schottky
#@@enum:type:zener
#@@enum:type:tunnel
#@@enum:type:varactor
#@@optional:type
#@@default:type normal
#@@preview_args:type 300

#@@param:dia body diameter - affects silk symbol size
#@@dim:dia
#@@optional:dia
#@@default:dia spacing/12

#@@param:aspect silk symbol aspect: total width expressed as a portion of spacing
#@@optional:aspect
#@@default:aspect spacing/6


#@@include common_subc.awk

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/alf.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

