#!/bin/sh

#@@example dip(18)

#@@purpose Generate classic DIP packages.

#@@desc Generate thru-hole DIP packages with variable number of pins and
#@@desc row spacing
#@@params n, spacing, pitch

#@@param:n number of pins

#@@param:spacing spacing between the two rows of pins
#@@dim:spacing
#@@optional:spacing
#@@default:spacing 100 mil

#@@param:pitch spacing between two pins in the same row
#@@dim:pitch
#@@optional:pitch
#@@default:pitch 100 mil

#@@param:3dmodules 1=socket, 2=IC, 3=socket+IC
#@@optional:3dmodules
#@@default:3dmodules 1

#@@param:3dpindia pin diameter on the 3d model
#@@dim:3dpindia
#@@optional:3dpindia

#@@include common_subc.awk

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/dip.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

