#!/bin/sh

# Reference: Microchip Packaging Specification DS00000049BX (en012702.pdf), MSOP

#@@example msop(8)

#@@purpose Generate MSOP packages.

#@@desc Generate MSOP packages with variable number of pins and
#@@desc row spacing

#@@include so
#@@include common_subc.awk

#@@over@default:pad_spacing 0.65 mm
#@@over@default:row_spacing 4.9 mm
#@@over@default:int_bloat 0.6 mm
#@@over@default:ext_bloat 0.6 mm
#@@over@default:pad_thickness 0.45 mm


defaults=""
defaults="$defaults?pad_spacing=0.65mm,"
defaults="$defaults?row_spacing=4.9mm,"
defaults="$defaults?int_bloat=0.6mm,"
defaults="$defaults?ext_bloat=0.4mm,"
defaults="$defaults?rarc=25,"
defaults="$defaults?silk_ext_x=18,"
defaults="$defaults?silk_ext_y=22,"
defaults="$defaults?pad_thickness=0.45mm,"
defaults="$defaults?3dbody=msop"


awk -f `dirname $0`/common_subc.awk -f `dirname $0`/so.awk -v "args=$defaults,$*" -v gen=`basename $0` -v "genfull=$0"

