#!/bin/sh

# Reference: Microchip Packaging Specification DS00000049BX (en012702.pdf), QSOP

#@@example qsop(14)

#@@purpose Generate QSOP packages.

#@@desc Generate QSOP packages with variable number of pins and
#@@desc row spacing

#@@include so
#@@include common_subc.awk

#@@over@default:pad_spacing 25 mil
#@@over@default:row_spacing 213 mil
#@@over@default:int_vloat 22 mil
#@@over@default:ext_bloat 23 mil
#@@over@default:pad_thickness 16 mil

defaults=""
defaults="$defaults?pad_spacing=25mil,"
defaults="$defaults?row_spacing=213mil,"
defaults="$defaults?int_bloat=22mil,"
defaults="$defaults?ext_bloat=23mil,"
defaults="$defaults?rarc=25,"
defaults="$defaults?silk_ext_x=18,"
defaults="$defaults?silk_ext_y=22,"
defaults="$defaults?pad_thickness=16mil,"
defaults="$defaults?3dbody=qsop"


awk -f `dirname $0`/common_subc.awk -f `dirname $0`/so.awk -v "args=$defaults,$*" -v gen=`basename $0` -v "genfull=$0"

