#!/bin/sh

#@@example rcy(300,bar+)

#@@purpose Generate radial lead through-hole component

#@@desc Generate radial lead through-hole component with 2 pins (typical use: electrolytic caps)
#@@params spacing,pol,dia

#@@param:spacing spacing between the two pins
#@@dim:spacing

#@@param:pol how to mark polarity:  (optional; default: sign)
#@@enum:pol:none no marking
#@@enum:pol:sign print + next to pin 1 and - next to pin 2
#@@enum:pol:bar+ draw a bar inside the circle, around pin 2
#@@enum:pol:bar- draw a bar inside the circle, around pin 1
#@@enum:pol:bar same as bar+
#@@enum:pol:bar+sign bar+ and sign combined
#@@enum:pol:bar-sign bar- and sign combined
#@@optional:pol
#@@default:pol sign
#@@preview_args:pol 300

#@@param:dia body diameter - affects the silk circle
#@@optional:dia
#@@default:dia spacing*2

#@@include common_subc.awk

awk -f `dirname $0`/common_subc.awk -f `dirname $0`/rcy.awk -v "args=$*" -v gen=`basename $0` -v "genfull=$0"

