/*** generated by pcb-rnd using export_c_draw ***/
{
	rnd_color_t clr;
/* Layer #0: 'top' */
	rnd_color_load_int(&clr, 228, 93, 93, 255);
	rnd_render->set_color(gc, &clr);
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.5080));
	rnd_render->draw_arc(gc, RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(4.3180), RND_MM_TO_COORD(4.3180), 132.510447, 272.489553);
/* Layer #6: 'top' */
	rnd_color_load_int(&clr, 0, 0, 0, 255);
	rnd_render->set_color(gc, &clr);
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(1.3970), RND_MM_TO_COORD(1.3970), RND_MM_TO_COORD(0.6350)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(6.3500)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(5.3340), RND_MM_TO_COORD(4.8260), RND_MM_TO_COORD(5.0800)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(2.6670), RND_MM_TO_COORD(2.6670), RND_MM_TO_COORD(1.9050)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(6.3500));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(2.2860));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(1.9050), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.9050), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(2.1590), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.1590), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(2.2860), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.2860), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(2.2860), RND_MM_TO_COORD(6.7310));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.5908), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(2.5908), RND_MM_TO_COORD(7.0104));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.5908), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(2.5908), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.3528), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(3.3528), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.2258), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(3.3528), RND_MM_TO_COORD(7.6200));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.9718), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(3.2258), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.8448), RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(2.9718), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.8448), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(2.8448), RND_MM_TO_COORD(7.6200));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.8448), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(2.9718), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.9718), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(3.2258), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.2258), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(3.3528), RND_MM_TO_COORD(7.3660));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.7846), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(3.7846), RND_MM_TO_COORD(7.6200));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.7846), RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(3.9116), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.6576), RND_MM_TO_COORD(7.1120), RND_MM_TO_COORD(3.9116), RND_MM_TO_COORD(7.1120));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.1656), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(4.1656), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.1656), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(4.2926), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.2926), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(4.5466), RND_MM_TO_COORD(7.2390));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.5466), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(4.6736), RND_MM_TO_COORD(7.3660));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.6736), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(4.6736), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.5880), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(6.4770));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.5880), RND_MM_TO_COORD(5.8420), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(5.8420));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(5.8420));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(5.4102), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(5.0292));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(5.5372), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(5.4102));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(5.5372), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(5.5372));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(5.5372), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(5.4102));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(5.4102), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(5.1562));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(5.1562), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(5.0292));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(5.5372), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(5.0292));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(5.0292), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(5.0292));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.8420), RND_MM_TO_COORD(4.7244), RND_MM_TO_COORD(5.8674), RND_MM_TO_COORD(4.7244));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(4.7244), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(4.7244));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(4.0894), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.9624));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(4.3434), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(4.0894));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(4.4704), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(4.3434));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(4.4704), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(4.4704));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(4.4704), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(4.3434));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(4.3434), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(4.0894));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(4.0894), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(3.9624));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.8580), RND_MM_TO_COORD(4.4704), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(4.3434));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(4.3434), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(4.0894));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(4.0894), RND_MM_TO_COORD(6.8580), RND_MM_TO_COORD(3.9624));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(3.9624), RND_MM_TO_COORD(6.8580), RND_MM_TO_COORD(3.9624));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.5880), RND_MM_TO_COORD(3.6576), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(3.6576));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.6576), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(3.5306));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(3.5306), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(3.2766));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(3.2766), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.1496));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.1496), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(3.1496));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.5880), RND_MM_TO_COORD(2.7178), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(2.7178));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(2.7178), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(2.5908));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(2.8448), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(2.5908));
}
