/*** generated by pcb-rnd using export_c_draw ***/
{
	rnd_color_t clr;
/* Layer #0: 'top' */
	rnd_color_load_int(&clr, 228, 93, 93, 255);
	rnd_render->set_color(gc, &clr);
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.7940), RND_MM_TO_COORD(4.9530), RND_MM_TO_COORD(2.7940), RND_MM_TO_COORD(6.7310));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.7940), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(3.0480), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.5400), RND_MM_TO_COORD(5.7150), RND_MM_TO_COORD(3.0480), RND_MM_TO_COORD(5.7150));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.8100), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.5560), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(3.8100), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.5560), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.5560), RND_MM_TO_COORD(6.7310));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.5560), RND_MM_TO_COORD(6.2230), RND_MM_TO_COORD(3.8100), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.8100), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(4.3180), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.3180), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(6.2230));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.5560), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(6.4770));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(6.4770), RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(6.2230));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.1816), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(6.1976), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.1816), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(6.1976), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.0612), RND_MM_TO_COORD(4.9530), RND_MM_TO_COORD(7.0612), RND_MM_TO_COORD(6.7310));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.0612), RND_MM_TO_COORD(6.7310), RND_MM_TO_COORD(7.3152), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.8072), RND_MM_TO_COORD(5.7150), RND_MM_TO_COORD(7.3152), RND_MM_TO_COORD(5.7150));
/* Layer #6: 'top' */
	rnd_color_load_int(&clr, 0, 0, 0, 255);
	rnd_render->set_color(gc, &clr);
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(4.5720), RND_MM_TO_COORD(3.8100)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(2.2860), RND_MM_TO_COORD(2.7940), RND_MM_TO_COORD(2.5400)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_arc(gc, RND_MM_TO_COORD(4.4450), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(3.8100), RND_MM_TO_COORD(3.8100), 180.000000, 90.000000);
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6982), RND_MM_TO_COORD(2.5116), RND_MM_TO_COORD(7.0516), RND_MM_TO_COORD(3.1582));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9708), RND_MM_TO_COORD(3.0774), RND_MM_TO_COORD(7.1325), RND_MM_TO_COORD(3.0774));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.8092), RND_MM_TO_COORD(2.9158), RND_MM_TO_COORD(6.9708), RND_MM_TO_COORD(3.0774));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.8092), RND_MM_TO_COORD(2.7541), RND_MM_TO_COORD(6.8092), RND_MM_TO_COORD(2.9158));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9708), RND_MM_TO_COORD(2.5925), RND_MM_TO_COORD(6.8092), RND_MM_TO_COORD(2.7541));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9708), RND_MM_TO_COORD(2.5925), RND_MM_TO_COORD(7.1325), RND_MM_TO_COORD(2.5925));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.1325), RND_MM_TO_COORD(2.5925), RND_MM_TO_COORD(7.2941), RND_MM_TO_COORD(2.7541));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.2941), RND_MM_TO_COORD(2.7541), RND_MM_TO_COORD(7.2941), RND_MM_TO_COORD(2.9158));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.3264), RND_MM_TO_COORD(3.4330), RND_MM_TO_COORD(7.5689), RND_MM_TO_COORD(3.6755));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.3264), RND_MM_TO_COORD(3.2714), RND_MM_TO_COORD(7.3264), RND_MM_TO_COORD(3.4330));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4881), RND_MM_TO_COORD(3.1097), RND_MM_TO_COORD(7.3264), RND_MM_TO_COORD(3.2714));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4881), RND_MM_TO_COORD(3.1097), RND_MM_TO_COORD(7.6497), RND_MM_TO_COORD(3.1097));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6497), RND_MM_TO_COORD(3.1097), RND_MM_TO_COORD(7.8114), RND_MM_TO_COORD(3.2714));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.8114), RND_MM_TO_COORD(3.2714), RND_MM_TO_COORD(7.8114), RND_MM_TO_COORD(3.4330));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4073), RND_MM_TO_COORD(3.1906), RND_MM_TO_COORD(7.7306), RND_MM_TO_COORD(3.5138));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.7306), RND_MM_TO_COORD(3.5138), RND_MM_TO_COORD(7.8114), RND_MM_TO_COORD(3.4330));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.3286), RND_MM_TO_COORD(3.7886), RND_MM_TO_COORD(8.3286), RND_MM_TO_COORD(3.9503));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.1670), RND_MM_TO_COORD(3.6270), RND_MM_TO_COORD(8.3286), RND_MM_TO_COORD(3.7886));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0054), RND_MM_TO_COORD(3.6270), RND_MM_TO_COORD(8.1670), RND_MM_TO_COORD(3.6270));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0054), RND_MM_TO_COORD(3.6270), RND_MM_TO_COORD(7.8437), RND_MM_TO_COORD(3.7886));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.8437), RND_MM_TO_COORD(3.7886), RND_MM_TO_COORD(7.8437), RND_MM_TO_COORD(3.9503));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.8437), RND_MM_TO_COORD(3.9503), RND_MM_TO_COORD(8.0054), RND_MM_TO_COORD(4.1119));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0054), RND_MM_TO_COORD(4.1119), RND_MM_TO_COORD(8.1670), RND_MM_TO_COORD(4.1119));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6012), RND_MM_TO_COORD(4.0311), RND_MM_TO_COORD(7.6012), RND_MM_TO_COORD(4.1928));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6012), RND_MM_TO_COORD(4.1928), RND_MM_TO_COORD(7.7629), RND_MM_TO_COORD(4.3544));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.7629), RND_MM_TO_COORD(4.3544), RND_MM_TO_COORD(7.9245), RND_MM_TO_COORD(4.3544));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.4095), RND_MM_TO_COORD(3.8695), RND_MM_TO_COORD(7.9245), RND_MM_TO_COORD(4.3544));
}
