/*** generated by pcb-rnd using export_c_draw ***/
{
	rnd_color_t clr;
/* Layer #0: 'top' */
	rnd_color_load_int(&clr, 228, 93, 93, 255);
	rnd_render->set_color(gc, &clr);
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(0.7620), RND_MM_TO_COORD(0.8890), RND_MM_TO_COORD(0.7620), RND_MM_TO_COORD(1.7780));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(0.7620), RND_MM_TO_COORD(1.7780), RND_MM_TO_COORD(0.8890), RND_MM_TO_COORD(1.9050));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(0.6350), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(0.8890), RND_MM_TO_COORD(1.2700));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(1.9050), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.9050));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.1430), RND_MM_TO_COORD(1.7780), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(1.9050));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.1430), RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(1.1430), RND_MM_TO_COORD(1.7780));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.1430), RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(1.3970));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(1.3970), RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(1.3970));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.5240), RND_MM_TO_COORD(1.3970), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.5240));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.1430), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.6510));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.6510), RND_MM_TO_COORD(1.5240));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.9558), RND_MM_TO_COORD(1.3970), RND_MM_TO_COORD(2.4638), RND_MM_TO_COORD(1.9050));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.9558), RND_MM_TO_COORD(1.9050), RND_MM_TO_COORD(2.4638), RND_MM_TO_COORD(1.3970));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.8956), RND_MM_TO_COORD(0.8890), RND_MM_TO_COORD(2.8956), RND_MM_TO_COORD(1.7780));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.8956), RND_MM_TO_COORD(1.7780), RND_MM_TO_COORD(3.0226), RND_MM_TO_COORD(1.9050));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.7686), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(3.0226), RND_MM_TO_COORD(1.2700));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.1120), RND_MM_TO_COORD(5.8420), RND_MM_TO_COORD(7.1120), RND_MM_TO_COORD(8.5090));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.1120), RND_MM_TO_COORD(8.5090), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(8.8900));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(7.2390), RND_MM_TO_COORD(6.9850));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(8.8900), RND_MM_TO_COORD(8.0010), RND_MM_TO_COORD(8.8900));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4930), RND_MM_TO_COORD(8.5090), RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(8.8900));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4930), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(7.4930), RND_MM_TO_COORD(8.5090));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4930), RND_MM_TO_COORD(7.7470), RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(7.3660));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6200), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(7.8740), RND_MM_TO_COORD(7.3660));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.8740), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(8.0010), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4930), RND_MM_TO_COORD(8.1280), RND_MM_TO_COORD(8.0010), RND_MM_TO_COORD(8.1280));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0010), RND_MM_TO_COORD(8.1280), RND_MM_TO_COORD(8.0010), RND_MM_TO_COORD(7.7470));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.3058), RND_MM_TO_COORD(7.3660), RND_MM_TO_COORD(8.8138), RND_MM_TO_COORD(8.8900));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.3058), RND_MM_TO_COORD(8.8900), RND_MM_TO_COORD(8.8138), RND_MM_TO_COORD(7.3660));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.2456), RND_MM_TO_COORD(5.8420), RND_MM_TO_COORD(9.2456), RND_MM_TO_COORD(8.5090));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.2456), RND_MM_TO_COORD(8.5090), RND_MM_TO_COORD(9.3726), RND_MM_TO_COORD(8.8900));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.1186), RND_MM_TO_COORD(6.9850), RND_MM_TO_COORD(9.3726), RND_MM_TO_COORD(6.9850));
/* Layer #6: 'top' */
	rnd_color_load_int(&clr, 0, 0, 0, 255);
	rnd_render->set_color(gc, &clr);
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(5.5226), RND_MM_TO_COORD(5.8818), RND_MM_TO_COORD(6.2411)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(6.5168), RND_MM_TO_COORD(6.1576), RND_MM_TO_COORD(6.8761)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.3795), RND_MM_TO_COORD(3.0145), RND_MM_TO_COORD(5.9716), RND_MM_TO_COORD(6.6066));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.4450), RND_MM_TO_COORD(4.4450), RND_MM_TO_COORD(4.9530), RND_MM_TO_COORD(4.4450));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.4450), RND_MM_TO_COORD(4.6990), RND_MM_TO_COORD(4.9530), RND_MM_TO_COORD(4.6990));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.2578), RND_MM_TO_COORD(4.1910), RND_MM_TO_COORD(5.3848), RND_MM_TO_COORD(4.0640));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.3848), RND_MM_TO_COORD(4.0640), RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(4.0640));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(4.0640), RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.1910));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.9530));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.3848), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(5.0800));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.2578), RND_MM_TO_COORD(4.9530), RND_MM_TO_COORD(5.3848), RND_MM_TO_COORD(5.0800));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.3848), RND_MM_TO_COORD(4.5212), RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(4.5212));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.1910), RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.3942));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.6482), RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.9530));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.6482), RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(4.5212));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.7658), RND_MM_TO_COORD(4.3942), RND_MM_TO_COORD(5.6388), RND_MM_TO_COORD(4.5212));
}
