/*** generated by pcb-rnd using export_c_draw ***/
{
	rnd_color_t clr;
/* Layer #0: 'top' */
	rnd_color_load_int(&clr, 228, 93, 93, 255);
	rnd_render->set_color(gc, &clr);
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.6096));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(3.6830), RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(8.2550));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(3.6830), RND_MM_TO_COORD(2.3368), RND_MM_TO_COORD(2.1590));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(2.3368), RND_MM_TO_COORD(2.1590), RND_MM_TO_COORD(4.0132), RND_MM_TO_COORD(2.1590));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(4.0132), RND_MM_TO_COORD(2.1590), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(3.6830));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(3.6830), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(8.2550));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(1.2700), RND_MM_TO_COORD(5.2070), RND_MM_TO_COORD(5.0800), RND_MM_TO_COORD(5.2070));
/* Layer #6: 'top' */
	rnd_color_load_int(&clr, 0, 0, 0, 255);
	rnd_render->set_color(gc, &clr);
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(5.2070)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(6.3500)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	{ /* polygon of 3 points */
		rnd_coord_t x[] = {
			RND_MM_TO_COORD(4.1910), RND_MM_TO_COORD(4.1910), RND_MM_TO_COORD(4.9530)
		};
		rnd_coord_t y[] = {
			RND_MM_TO_COORD(6.6040), RND_MM_TO_COORD(6.0960), RND_MM_TO_COORD(6.3500)
		};
		rnd_render->fill_polygon(gc, 3, x, y);
	}
	rnd_hid_set_line_cap(gc, rnd_cap_round);
	rnd_hid_set_line_width(gc, RND_MM_TO_COORD(0.1016));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(3.6830), RND_MM_TO_COORD(6.3500), RND_MM_TO_COORD(9.6520), RND_MM_TO_COORD(6.3500));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.4229), RND_MM_TO_COORD(5.2578), RND_MM_TO_COORD(5.4229), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.4229), RND_MM_TO_COORD(5.8801), RND_MM_TO_COORD(5.5118), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.3340), RND_MM_TO_COORD(5.5245), RND_MM_TO_COORD(5.5118), RND_MM_TO_COORD(5.5245));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.6896), RND_MM_TO_COORD(5.2578), RND_MM_TO_COORD(5.6896), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.6896), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(5.7785), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.7785), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(5.9563), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(5.9563), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(6.0452), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.0452), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(6.0452), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2586), RND_MM_TO_COORD(5.4356), RND_MM_TO_COORD(6.2586), RND_MM_TO_COORD(5.4534));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.2586), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(6.2586), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.5253), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(6.7920), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4364), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(6.5253), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4364), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(6.4364), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.4364), RND_MM_TO_COORD(5.8801), RND_MM_TO_COORD(6.5253), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(6.5253), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(6.7920), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.0053), RND_MM_TO_COORD(5.2578), RND_MM_TO_COORD(7.0053), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.0053), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(7.2720), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.0053), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(7.1831), RND_MM_TO_COORD(5.5245));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.5743), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(7.5743), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.5743), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(7.6632), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.6632), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(7.7521), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.7521), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(7.8410), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.8410), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(7.8410), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(7.4854), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(7.5743), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.1432), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(8.4099), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0543), RND_MM_TO_COORD(5.8801), RND_MM_TO_COORD(8.1432), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0543), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(8.0543), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0543), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(8.1432), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.1432), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(8.3210), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.3210), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(8.4099), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.0543), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(8.4099), RND_MM_TO_COORD(5.7912));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.4099), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(8.4099), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(9.0678), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(9.0678), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.7912));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.6233), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.7912));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.6233), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.9789), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(9.0678), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(8.6233), RND_MM_TO_COORD(5.8801), RND_MM_TO_COORD(8.7122), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.9690));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.9690), RND_MM_TO_COORD(9.7257), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(9.7257), RND_MM_TO_COORD(5.8801));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.7912), RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.7912));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.2812), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.7912));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.2812), RND_MM_TO_COORD(5.7023), RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.6134));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.6368), RND_MM_TO_COORD(5.6134), RND_MM_TO_COORD(9.7257), RND_MM_TO_COORD(5.7023));
	rnd_render->draw_line(gc, RND_MM_TO_COORD(9.2812), RND_MM_TO_COORD(5.8801), RND_MM_TO_COORD(9.3701), RND_MM_TO_COORD(5.9690));
}
